
version: 2

sources:
  - name: JobTeaser
    schema: JobTeaser
    tables: 
      - name: candidate_status
        identifier: candidate_status_update
        description: 
      - name: dim_schools
        identifier: dim_schools
      - name: optin
        identifier: optin

     