version: 2

sources:
  - name: JobTeaser
    schema: JobTeaser
    tables:
      - name: candidate_status
        identifier: candidate_status_update
        columns:
          - name: user_id
            description: student id, 31485 unique Id
          - name: receive_time
            description: based on student status (when student indicate intresse in a job)
          - name: shortlist_id
            description: ID for shortisted student
          - name: status_update
            description: status once the student has maked that they are looking for job opportunities
          - name: cause
            description: action made by student or recrutier once email is send
          - name: school_id
            description: student's school ID
          - name: current_sign_in_at
            description: Last time student connected on the platform
      - name: dim_schools
        description: students schools and country details
        columns:
          - name: school_id
            description: id of the school
          - name: is_cc
            description: is the cc partner with JT or not
          - name: intranet_school_id
            description: if JT public site -> id of school with cc
          - name: jt_country
            description: country of the school
          - name: jt_intranet_status
            description:
          - name: jt_school_type
            description: type of school
      - name: optin
        identifier: optin
        columns:
          - name: user_id
            description: ID of the studentCount Distinct is 376552
          - name: receive_time
            description: Time when the student is 'open for opportunities'
          - name: cause
            description: student manually opt-in/opt-out toggleauto-no-answer, if student does not answer to a Shortlist -> he is automatically opt-out
          - name: active
            description: TRUE if it is opt-in FALSE otherwise
          - name: school_id
            description: 2326 different school ID's
          - name: current_sign_in_at
            description: last student connection date
          - name: resume_uploaded
            description: The student has uploaded his CV on JT
models:
  - name: optin_cleaned_view
    description: we kept the last status row per user_id
  - name: candidate_clean_view
    description: we kept the last status row per user_id and shortliste_id
  - name: optin_candidate_merged
    description: joined the tables optin_cleaned_view, candidate_clen_view and dim_schools. Primary key is user_id
  - name: funnel_status
    description: from the optin_candidate_merged, we created categories for shorlisted user id, status update and school types
  - name: funnel_status_column
    description: merged the colunms user_id, jt_country, jt_school_type, is_cc, jt_school_type_name, approved_colnum , optin_cause and opt_receveived_name using UNION ALL to create a table that allowed us to have all the categories status without having missing data.
  - name: maximize_shortlists
    description: table that showed the amount of shortliste we have per student
  - name: shortlisted_by_schooltype
    description: subquery with the table funnel_status_column
